### ISSUE TITLE
😍 Blown Away By Your Job Application Tools like Cover Letter And Resume 😍

### ISSUE THREAD

**Issue by emilyb2** [posquit0/ama#9]
Your Cover Letter is literally so cool. All your job application tools are. I emailed you. Please answer. 

I'd love to "buy you a coffee" or several ☕️'s, and help a little on your sponsorship efforts for your projects, if you would help me find or understand some products that would build some cover letters and resumes for me tailored to the ATS –– you know the more cool tech stuff it has in it AI, Machine Learning, Sentient Analysis, Etc., the better the cover letter or resume would be. Or just simply what you think the best tools available are –– to mitigate the job application process –– I'm a struggling writer. Hopefully hear from you on email, because I never am content with anything, and those documents were literally the most perfect things that I have ever seen in my life. Please help me. 

P.S. what a cute idea –– buy me a coffee, I'd love to! 

My main problem is that I don't understand GitHub like at all yet –– that's why I'm asking an expert.

**Comment by posquit0** [comment]
Hi,

First of all, I'm glad to hear that you love my cover letter template! 😄 

I just understand that you want to know how exactly make your own cover letter with my template.
Is it what I'm thinking of?

Could you let me know where did you see my cover letter and what makes you difficult to use the template?
Did you see the [GitHub repository(posquit0/AwesomeCV)](https://github.com/posquit0/Awesome-CV)? Do you know the basis of LaTeX? (because AwesomeCV template is based on LaTeX)

Thanks! :)
